version: '3.1'
services:
  w3champions-ui-dev:
    image: modmoto/w3champions-ui:#{TAG}#
    container_name: w3c-website-pr-#{PR_NAME}#
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=#{PR_NAME}#.w3champions.com
      - LETSENCRYPT_HOST=#{PR_NAME}#.w3champions.com
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com
      - BASE_URL=https://statistic-service.test.w3champions.com/
      - IDENTIFICATION_URL=https://identification-service.test.w3champions.com/
      - LAUNCHER_UPDATE_URL=https://update-service.test.w3champions.com/api/
      - INGAME_STATIC_RESOURCES_URL=https://w3champions.wc3.tools/test/integration/
      - BNET_API_CLIENT_ID=d7bd6dd46e2842c8a680866759ad34c2
      - S3_ACESS_KEY=#{S3_ACESS_KEY}#
      - S3_SECRET_KEY=#{S3_SECRET_KEY}#
      - STAGE=dev
      - SITE_CDN_URL=https://w3champions.wc3.tools/test/site

networks:
  default:
    external:
      name: nginx-proxy
