version: '2'
services:
  frontproxy:
    image: jwilder/nginx-proxy:latest
    container_name: frontproxy
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
